### ISSUE TITLE
Code style?

### ISSUE THREAD

**Issue by zvezdochiot** [ksharindam/pdfcook#3]
⚠️ It's not a problem! Question for consideration! 

I always use `astyle` ( http://astyle.sourceforge.net/ ) to style my code:
```sh
astyle --style=allman *.h *.c *.cpp
```
See also https://github.com/uncrustify/uncrustify .

**Comment by ksharindam** [comment]
Did not know about that.
I will check it.
I use both Allman and K&R style in single file depending on the code readability.

**Comment by zvezdochiot** [comment]
Getting rid of all < TAB > is also desirable:
```sh
sed -i -e 's/\t/    /g' *.h *.c *.cpp    # \t -> 4 space
```

**Comment by ksharindam** [comment]
Did not notice that my code has so many tabs (may copy-paste issue).
Though i never use tabs (the editor use spaces when i press tab key).
I will replace all tabs.

**Comment by zvezdochiot** [comment]
Close it as you see fit, or by commit, in the form of "fix".
