### ISSUE TITLE
Info?

### ISSUE THREAD

**Issue by zvezdochiot** [ksharindam/pdfcook#4]
https://github.com/ksharindam/pdfcook/blob/634c06952557bf88e5d4eda17b6dc31176043e6d/src/cmd_exec.cpp#L225
This statement should not require an output file. But it's require.

**Comment by ksharindam** [comment]
That is a command line parsing problem.
When one arg is passed, it is assumed as a filename.
When two args are passed, first is assumed as input file, and second is output filename.
And when three args are passed, first is assumed as command, and rest are input and output filename.
So when you pass two args, first arg must be input filename.

If you dont want to pass output filename, you can use /dev/null as output filename.

**Comment by zvezdochiot** [comment]
Overdue.
